[CmdletBinding()]
param([ValidateSet('WindowsPowerShell','Pwsh')][string]$Engine = 'Pwsh')
$ErrorActionPreference = 'Stop'
$runner = Join-Path (Split-Path $PSScriptRoot -Parent) 'run-all.ps1'
$enginePath = if ($Engine -eq 'Pwsh') { (Get-Command pwsh.exe).Source } else { (Get-Command powershell.exe).Source }
$root = Join-Path ([IO.Path]::GetTempPath()) ('clipwarp-runner-fixture-' + [guid]::NewGuid().ToString('N'))
[void][IO.Directory]::CreateDirectory($root)
function Check($Condition, [string]$Message) { if (-not $Condition) { throw $Message }; Write-Host "PASS: $Message" }
try {
    $suites = Join-Path $root 'suites'; [void][IO.Directory]::CreateDirectory($suites)
    [IO.File]::WriteAllText((Join-Path $suites '01-pass.Tests.ps1'), @'
if (-not $env:CLIPWARP_TEST_ROOT) { throw 'Missing isolation root' }
foreach ($name in @('TEMP','TMP','USERPROFILE','HOME','APPDATA','LOCALAPPDATA','PROGRAMDATA')) {
    $value = [Environment]::GetEnvironmentVariable($name)
    if (-not $value.StartsWith($env:CLIPWARP_TEST_ROOT + '\', [StringComparison]::OrdinalIgnoreCase)) { throw "Unsafe environment: $name" }
}
if (-not $PROFILE.CurrentUserCurrentHost.StartsWith($env:CLIPWARP_TEST_ROOT)) { throw 'Unsafe profile' }
Write-Output ('ROOT=' + $env:CLIPWARP_TEST_ROOT)
Write-Output 'captured-standard-output'
[Console]::Error.WriteLine('captured-standard-error')
exit 0
'@)
    [IO.File]::WriteAllText((Join-Path $suites '02-fail.Tests.ps1'), 'exit 7')
    [IO.File]::WriteAllText((Join-Path $suites '03-timeout.Tests.ps1'), @'
$exe = [Diagnostics.Process]::GetCurrentProcess().MainModule.FileName
$code = [Convert]::ToBase64String([Text.Encoding]::Unicode.GetBytes('Start-Sleep -Seconds 90'))
$p = Start-Process -FilePath $exe -ArgumentList ('-NoProfile -NonInteractive -EncodedCommand ' + $code) -PassThru
Write-Output ('OWNED=' + $p.Id)
Start-Sleep -Seconds 90
'@)
    [IO.File]::WriteAllText((Join-Path $suites '04-throw.Tests.ps1'), "throw 'fixture exception'")
    [IO.File]::WriteAllText((Join-Path $suites '05-after.Tests.ps1'), "Write-Output 'continued-after-timeout'; exit 0")
    $resultPath = Join-Path $root 'results.json'
    & $enginePath -NoProfile -NonInteractive -ExecutionPolicy Bypass -File $runner -Engine $Engine -SuiteDirectory $suites -SuiteTimeoutSeconds 5 -ResultsPath $resultPath | Out-Null
    Check ($LASTEXITCODE -eq 1) 'runner returns failure for failed/timed-out suites'
    $report = Get-Content -LiteralPath $resultPath -Raw | ConvertFrom-Json
    Check ($report.SchemaVersion -eq 1 -and $report.Total -eq 5 -and $report.Passed -eq 2 -and $report.Failed -eq 3 -and $report.TimedOut -eq 1) 'machine-readable aggregate matches fixtures'
    Check ($report.Suites[0].Stdout -match 'captured-standard-output' -and $report.Suites[0].Stderr -match 'captured-standard-error') 'both output streams captured'
    Check ($report.Suites[1].ExitCode -eq 7) 'explicit suite exit code retained'
    Check ($report.Suites[3].Stderr -match 'fixture exception') 'terminating errors fail and retain diagnostics'
    Check ($report.Suites[4].Stdout -match 'continued-after-timeout') 'runner continues after timeout'
    $ownedMatch = [regex]::Match($report.Suites[2].Stdout, 'OWNED=(\d+)')
    Check $ownedMatch.Success 'timeout fixture started owned descendant'
    Start-Sleep -Milliseconds 250
    Check (-not (Get-Process -Id ([int]$ownedMatch.Groups[1].Value) -ErrorAction SilentlyContinue)) 'owned descendant terminated on timeout'
    $rootMatch = [regex]::Match($report.Suites[0].Stdout, 'ROOT=([^\r\n]+)')
    Check ($rootMatch.Success -and -not (Test-Path -LiteralPath $rootMatch.Groups[1].Value)) 'generated temporary root cleaned'
    Check (-not $report.CleanupError) 'cleanup reports no error'
    & $enginePath -NoProfile -NonInteractive -ExecutionPolicy Bypass -File $runner -Engine $Engine -SuiteDirectory $suites -Suite '01-*' -ResultsPath $resultPath | Out-Null
    Check ($LASTEXITCODE -eq 0) 'selected passing suite returns success'
    $selected = Get-Content -LiteralPath $resultPath -Raw | ConvertFrom-Json
    Check ($selected.Total -eq 1 -and $selected.Passed -eq 1) 'suite filter selects exactly one suite'
    Write-Host "Runner fixtures passed: $Engine"
} finally {
    # These fixture files are generated by this script and contain no reparse points.
    Remove-Item -LiteralPath $root -Recurse -Force
}
